"""
ingestion/transformer.py
--------------------------
Transforms raw connector records into normalised canonical field dicts
ready for UnifiedRecord construction.

Responsibilities
----------------
1. Resolve the entity_id from source-specific field names.
2. Strip / coerce common type mismatches (None → "", int → str).
3. Inject pipeline metadata (source_type, source_name, entity_type,
   schema_version).
4. Return a clean dict that maps 1-to-1 to UnifiedRecord fields.

The checksum and record_id are intentionally left to UnifiedRecord's
Pydantic validators (auto-computed on model construction).
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any

from src.ingestion.p2_framework.p2_config import SCHEMA_VERSION
from src.ingestion.p2_framework.schema import SourceType

logger = logging.getLogger("p2.transformer")

# ──────────────────────────────────────────────────────────────────────────────
# Field alias registry
# Maps source-specific field names → canonical "entity_id" field.
# Used when the connector's entity_id_field is not the primary key name.
# ──────────────────────────────────────────────────────────────────────────────
_ENTITY_ID_ALIASES: dict[SourceType, list[str]] = {
    SourceType.CSV:  ["CustomerID", "customer_id", "id", "ID", "Id", "order_id", "employee_id"],
    SourceType.JSON: ["id", "order_id", "customer_id", "ID", "orderId", "customerId"],
    SourceType.REST: ["id", "userId", "user_id", "ID"],
    SourceType.SQL:  ["id", "employee_id", "emp_id", "ID"],
}


def transform(
    raw_record: dict[str, Any],
    source_type: SourceType,
    source_name: str,
    entity_type: str,
    entity_id_field: str,
) -> dict[str, Any]:
    """
    Normalise a raw connector dict into a dict suitable for UnifiedRecord.

    Parameters
    ----------
    raw_record      : Raw dict yielded by the connector.
    source_type     : SourceType enum (CSV/JSON/REST/SQL).
    source_name     : Logical source identifier.
    entity_type     : Business entity category.
    entity_id_field : Preferred entity-ID field name from the connector.

    Returns
    -------
    dict  — Contains all UnifiedRecord fields except `record_id` and
            `checksum` (those are auto-generated by the Pydantic model).

    Raises
    ------
    ValueError if entity_id cannot be resolved from the record.
    """
    # ── 1. Resolve entity_id ──────────────────────────────────────────────
    entity_id = _resolve_entity_id(raw_record, entity_id_field, source_type)

    # ── 2. Sanitise payload (make all values JSON-safe) ───────────────────
    clean_payload = _sanitise_payload(raw_record)

    # ── 3. Build canonical dict ───────────────────────────────────────────
    return {
        "source_type": source_type,
        "source_name": source_name,
        "ingested_at": datetime.now(timezone.utc),
        "entity_type": entity_type,
        "entity_id": str(entity_id),
        "payload": clean_payload,
        "schema_version": SCHEMA_VERSION,
    }


# ──────────────────────────────────────────────────────────────────────────────
# Internal helpers
# ──────────────────────────────────────────────────────────────────────────────

def _resolve_entity_id(
    record: dict[str, Any],
    preferred_field: str,
    source_type: SourceType,
) -> Any:
    """
    Attempt to find the entity_id in the following priority order:
    1. The connector's declared entity_id_field.
    2. Known aliases for the source_type.
    3. The first key in the record (last resort).

    Raises ValueError if record is empty.
    """
    # Priority 1: connector-declared field
    if preferred_field in record and record[preferred_field] not in (None, ""):
        return record[preferred_field]

    # Priority 2: known aliases
    for alias in _ENTITY_ID_ALIASES.get(source_type, []):
        if alias in record and record[alias] not in (None, ""):
            logger.debug(
                "Resolved entity_id via alias",
                extra={"alias": alias, "source_type": source_type.value},
            )
            return record[alias]

    # Priority 3: first key (fallback)
    if record:
        first_key = next(iter(record))
        first_val = record[first_key]
        if first_val not in (None, ""):
            logger.debug(
                "Resolved entity_id from first record key (fallback)",
                extra={"key": first_key, "source_type": source_type.value},
            )
            return first_val

    raise ValueError(
        f"Cannot resolve entity_id from record. "
        f"Tried field={preferred_field!r} and aliases. "
        f"Record keys: {list(record.keys())}"
    )


def _sanitise_payload(record: dict[str, Any]) -> dict[str, Any]:
    """
    Make all record values JSON-serialisable.
    - datetime → ISO string
    - bytes → hex string
    - None stays as None (JSON null)
    - Everything else is coerced via str() if needed
    """
    clean: dict[str, Any] = {}
    for key, value in record.items():
        str_key = str(key).strip() if key is not None else "_unknown"
        if isinstance(value, datetime):
            clean[str_key] = value.isoformat()
        elif isinstance(value, bytes):
            clean[str_key] = value.hex()
        elif isinstance(value, (str, int, float, bool)) or value is None:
            clean[str_key] = value
        else:
            # Complex types (list, nested dict after flattening, etc.)
            clean[str_key] = value
    return clean
